# Generated by Django 5.0.6 on 2024-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_manutencao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencao',
            name='custo',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='status',
            field=models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='agendado', max_length=20),
        ),
    ]
